In [ ]:
### NumPy = super-fast math engine for Python, mainly used to work with numbers, 
### arrays, vectors, and matrices.

### NumPy array → optimized C code underneath

### Used in Data science, ML, AI, Image processing etc



In [ ]:
### To use numpy we have install it first

### command - pip install numpy

In [2]:
!pip install numpy


In [ ]:
### After installing to use numpy we need to import it

import numpy as np  ### np is just an alias name (shortcut)

hello world


In [ ]:
import numpy as np

### creating array using numpy
### creating 1D array

array1 = np.array([1,2,3,4,5])
print(array1)
print(type(array1))
print(array1.shape)  ### output = (5,) as it a single dimension array 
### this have like 5 col


[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [ ]:
### now lets reshape the array from 1D to 2D

import numpy as np

array2 = array1.reshape(1,5) ### This means one row 5 col
print(array2)  ### output = [[1,2,3,4,5]]

### 2 D array always have 2 [[]] 
### 1 D array always have 1 []


[[1 2 3 4 5]]


In [ ]:
import numpy as np

array3 = np.array([[1,2,3,4,5]]) ### Here we have used 2 [[]]
print(array3.shape) ### This gives output as (1,5)


(1, 5)


In [ ]:
import numpy as np

### Here we will add multipul rows

array4 = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
print(array4)
print(array4.shape) ### Output will be (3,5)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
(3, 5)


In [14]:
### We will use some inbuilt functions

array5 = np.arange(0,10,2) ### this will create us an array [1,2,,4,6,8]

print(array5)
print(array5.shape)

array6 = np.arange(0,10,2).reshape(5,1) ### 5 rows one col
print(array6)

[0 2 4 6 8]
(5,)
[[0]
 [2]
 [4]
 [6]
 [8]]


In [20]:
### one2() inbuilt function, create a 2D array with all ones

array7 = np.ones((3,4)) ## you have to give rows and columns
print(array7)

array10 = np.zeros((3,3))
print(array10)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
### Identity matric , -> all the diagonal elements will be ones
### Function -> eye()

array8 = np.eye((3))
print(array8)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [24]:
### NumPy Vectorized Operations?

### Vectorized operations = doing math on entire arrays at once, without writing loops.

import numpy as np

array11 = np.array([1,15,1,4,19,23])
array12 = np.array([13,2,3,6,7,10])

print(f"addition = {array11 + array12}")  ### both arrays should have same elements

print(f"subtraction = {array11 - array12}")

print(f"Multi = {array11 * array12}")

print(f"Division = {array11 / array12}")


addition = [14 17  4 10 26 33]
subtraction = [-12  13  -2  -2  12  13]
Multi = [ 13  30   3  24 133 230]
Division = [0.07692308 7.5        0.33333333 0.66666667 2.71428571 2.3       ]


In [25]:
import numpy as np

arr = np.array([1,2,3,4,5])

newArr = arr * 2
print(newArr)

[ 2  4  6  8 10]


In [28]:
### Universal Functions

arr1 = np.array([1,2,3,4,5,6,25])

## spuareroot
print(np.sqrt(arr1))

## Exponential
print(np.exp(arr1))

[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 5.        ]
[2.71828183e+00 7.38905610e+00 2.00855369e+01 5.45981500e+01
 1.48413159e+02 4.03428793e+02 7.20048993e+10]


In [ ]:
### arrays slicing and indexing

arr3 = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
print(arr3)

print(arr3[0][0]) ## element in zero row , zero column
print(arr3[0]) ### give enter first row


### Now i want to select specific elements

print(arr3[1:])  ### this will print all the elements from row 1 to the end of the 2d array that why we used :

print(arr3[0:2]) ### this will start printing elements from row 0 to row 1 (I wont print 2nd row) and stop

print(arr3[1:,2:]) ### all number from row1 to end but also all numbers from col 2 to end

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
1
[1 2 3 4 5]
[[ 6  7  8  9 10]
 [11 12 13 14 15]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ 8  9 10]
 [13 14 15]]


In [ ]:
import numpy as np


Array = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(Array)

### now i only need 6,7 elemets as output

print(Array[1:2,1:3]) ### This will give 6,7

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[6 7]]


In [41]:
### modify the array

Array[0][0] = 100
print(Array)

Array[0:1,2:] = 100
print(Array)

[[100   2 100   4]
 [  5   6   7   8]
 [  9  10  11  12]]
[[100   2 100 100]
 [  5   6   7   8]
 [  9  10  11  12]]


In [43]:
### statistical concepts -- Normalization

### finding mean, medium and Standard deviation

data = np.array([1,2,3,4,5,6])

print(f"means = {np.mean(data)}")
print(f"median = {np.median(data)}")
print(f"Standard deviation = {np.std(data)}")

means = 3.5
median = 3.5
Standard deviation = 1.707825127659933


In [ ]:
### Logical Operations

data2 = np.array([1,2,3,4,5,6,7,8,9,10])

data2 > 5  ### applies to all the elements and return boolean values

data2[data2>5]  ### this will give us values which are greater than 5


array([False, False, False, False, False,  True,  True,  True,  True,
        True])