In [ ]:
# Module: NumPy Assignments
## Lesson: NumPy
### Assignment 1: Array Creation and Manipulation

In [ ]:
### 1. Create a NumPy array of shape (5, 5) filled with random integers between 
# 1 and 20. Replace all the elements in the third column with 1.

import numpy as np

array = np.random.randint(2,20,(5,5))

print(array)
print(array.shape)

[[16  2  6 12 16]
 [ 4 15 17  6 12]
 [ 2 15 11  9  5]
 [18  7 19 19  9]
 [ 6  2 15  9  5]]
(5, 5)


In [9]:
### 2. Create a NumPy array of shape (4, 4) with values from 1 to 16. 
# Replace the diagonal elements with 0.

array2 = np.arange(1,17).reshape(4,4)
print(array2) 

np.fill_diagonal(array2,0)

print(array2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[ 0  2  3  4]
 [ 5  0  7  8]
 [ 9 10  0 12]
 [13 14 15  0]]


In [ ]:
### Assignment 2: Array Indexing and Slicing

In [ ]:
### Create a NumPy array of shape (6, 6) with values from 1 to 36. 
# Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.

array3 = np.arange(1,37).reshape(6,6)
print(array3)

print(array3[1:6,2:5])

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
[[ 9 10 11]
 [15 16 17]
 [21 22 23]
 [27 28 29]
 [33 34 35]]
